server:
  port: 80
  servlet:
    context-path: /renta
  error:
    include-stacktrace: never
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    url: "jdbc:sqlserver://DESKTOP-54MBGKL:1433;databaseName=Renta;TrustServerCertificate=True;"
    username: "sa"
    password: "passwordsql"

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update